CREATE TABLE  "ADHERENT" 
   (	"ID_ADHERENT" NUMBER, 
	"NOM" VARCHAR2(4000) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(4000) NOT NULL ENABLE, 
	"CIN" VARCHAR2(4000), 
	"CNE" VARCHAR2(4000), 
	 CONSTRAINT "ADHERENT_PK" PRIMARY KEY ("ID_ADHERENT") ENABLE
   )
/
CREATE TABLE  "DEPARTEMENT" 
   (	"ID_DEPARTEMENT" NUMBER, 
	"DESIGNATION" VARCHAR2(2000) NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTEMENT_PK" PRIMARY KEY ("ID_DEPARTEMENT") ENABLE, 
	 CONSTRAINT "DEPARTEMENT_CON" UNIQUE ("DESIGNATION") ENABLE
   )
/
CREATE TABLE  "MATERIEL" 
   (	"ID_MATERIEL" NUMBER, 
	"DESIGNATION" VARCHAR2(2000) NOT NULL ENABLE, 
	"PRIXHT" NUMBER NOT NULL ENABLE, 
	"TVA" NUMBER NOT NULL ENABLE, 
	"CATEGORIE" VARCHAR2(2000) NOT NULL ENABLE, 
	"ETAT" VARCHAR2(2000) NOT NULL ENABLE, 
	"IMAGE" BLOB, 
	 CONSTRAINT "MATERIEL_PK" PRIMARY KEY ("ID_MATERIEL") ENABLE
   )
/
CREATE TABLE  "AFFECTER" 
   (	"ID_MATERIEL" NUMBER NOT NULL ENABLE, 
	"ID_DEPARTEMENT" NUMBER, 
	"DATE_AFFECTATION" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "AFFECTER_CON" PRIMARY KEY ("ID_MATERIEL", "ID_DEPARTEMENT", "DATE_AFFECTATION") ENABLE, 
	 CONSTRAINT "AFFECTER_FK2" FOREIGN KEY ("ID_MATERIEL")
	  REFERENCES  "MATERIEL" ("ID_MATERIEL") ENABLE, 
	 CONSTRAINT "AFFECTER_FK3" FOREIGN KEY ("ID_DEPARTEMENT")
	  REFERENCES  "DEPARTEMENT" ("ID_DEPARTEMENT") ENABLE
   )
/
CREATE TABLE  "AUTEUR" 
   (	"ID_AUTEUR" NUMBER, 
	"NOM" VARCHAR2(4000) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(4000), 
	"DATE_NAISSANCE" VARCHAR2(4000), 
	"NATIONALITE" VARCHAR2(4000), 
	 CONSTRAINT "AUTEUR_PK" PRIMARY KEY ("ID_AUTEUR") ENABLE
   )
/
CREATE TABLE  "CATEGORIE" 
   (	"CATEGORIE" VARCHAR2(4000), 
	 CONSTRAINT "CATEGORIE_CON" PRIMARY KEY ("CATEGORIE") ENABLE
   )
/
CREATE TABLE  "DEMANDE" 
   (	"ID_DEMANDE" NUMBER NOT NULL ENABLE, 
	"ID_DEPT" NUMBER NOT NULL ENABLE, 
	"CATEGORIE" VARCHAR2(4000) NOT NULL ENABLE, 
	"DATE_DEMANDE" DATE NOT NULL ENABLE, 
	"QUANTITE" NUMBER NOT NULL ENABLE, 
	"DECISION" VARCHAR2(4000), 
	"DATE_TRAITEMENT" DATE, 
	"NBR_AFFECTE" NUMBER, 
	 CONSTRAINT "DEMANDE_PK" PRIMARY KEY ("ID_DEMANDE") ENABLE, 
	 CONSTRAINT "DEMANDE_FK" FOREIGN KEY ("ID_DEPT")
	  REFERENCES  "DEPARTEMENT" ("ID_DEPARTEMENT") ENABLE, 
	 CONSTRAINT "DEMANDE_FK2" FOREIGN KEY ("CATEGORIE")
	  REFERENCES  "CATEGORIE" ("CATEGORIE") ENABLE
   )
/
CREATE TABLE  "LIVRE" 
   (	"ISBN" VARCHAR2(4000), 
	"TITRE" VARCHAR2(2000) NOT NULL ENABLE, 
	"LANGUE" VARCHAR2(2000) NOT NULL ENABLE, 
	"NBR_PAGE" NUMBER NOT NULL ENABLE, 
	"DATE_PARUTION" VARCHAR2(2000) NOT NULL ENABLE, 
	"IMAGE_LIVRE" VARCHAR2(4000), 
	 CONSTRAINT "LIVRE_PK" PRIMARY KEY ("ISBN") ENABLE
   )
/
CREATE TABLE  "EXEMPLAIRE" 
   (	"ID_EXEMPLAIRE" NUMBER, 
	"ETAT" VARCHAR2(16) NOT NULL ENABLE, 
	"ISBN" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "EXEMPLAIRE_PK" PRIMARY KEY ("ID_EXEMPLAIRE") ENABLE, 
	 CONSTRAINT "EXEMPLAIRE_CON" FOREIGN KEY ("ISBN")
	  REFERENCES  "LIVRE" ("ISBN") ENABLE
   )
/
CREATE TABLE  "EMPRUNTER" 
   (	"ID_ADHERENT" NUMBER, 
	"ID_EXEMPLAIRE" NUMBER, 
	"DATE_EMPRUNT" DATE NOT NULL ENABLE, 
	"DATE_RETOUR" DATE NOT NULL ENABLE, 
	"RENDU" VARCHAR2(16) NOT NULL ENABLE, 
	 CONSTRAINT "EMPRUNTER_PK" PRIMARY KEY ("ID_ADHERENT", "ID_EXEMPLAIRE", "DATE_EMPRUNT") ENABLE, 
	 CONSTRAINT "EMPRUNTER_CON" FOREIGN KEY ("ID_ADHERENT")
	  REFERENCES  "ADHERENT" ("ID_ADHERENT") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "EMPRUNTER_CON1" FOREIGN KEY ("ID_EXEMPLAIRE")
	  REFERENCES  "EXEMPLAIRE" ("ID_EXEMPLAIRE") ENABLE
   )
/
CREATE TABLE  "RESPONSABLE" 
   (	"ID_RESPONSABLE" NUMBER, 
	"NOM" VARCHAR2(4000), 
	"PRENOM" VARCHAR2(4000), 
	"GRADE" VARCHAR2(4000), 
	"CIN" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(2000) NOT NULL ENABLE, 
	 CONSTRAINT "RESPONSABLE_PK" PRIMARY KEY ("ID_RESPONSABLE") ENABLE
   )
/
CREATE TABLE  "GERER" 
   (	"ID_DEPARTEMENT" NUMBER, 
	"ID_RESPONSABLE" NUMBER, 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	 CONSTRAINT "GERER_CON" PRIMARY KEY ("ID_DEPARTEMENT", "ID_RESPONSABLE", "DATE_DEBUT") ENABLE, 
	 CONSTRAINT "GERER_FK" FOREIGN KEY ("ID_DEPARTEMENT")
	  REFERENCES  "DEPARTEMENT" ("ID_DEPARTEMENT") ENABLE, 
	 CONSTRAINT "GERER_FK2" FOREIGN KEY ("ID_RESPONSABLE")
	  REFERENCES  "RESPONSABLE" ("ID_RESPONSABLE") ENABLE
   )
/
CREATE TABLE  "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(30), 
	"OBJECT_NAME" VARCHAR2(30), 
	"OBJECT_ALIAS" VARCHAR2(65), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(30), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(30)
   )
/
CREATE TABLE  "PUBLIER" 
   (	"ISBN" VARCHAR2(4000), 
	"ID_AUTEUR" NUMBER, 
	 CONSTRAINT "PUBLIER_PK" PRIMARY KEY ("ISBN", "ID_AUTEUR") ENABLE, 
	 CONSTRAINT "PUBLIER_CON" FOREIGN KEY ("ISBN")
	  REFERENCES  "LIVRE" ("ISBN") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PUBLIER_CON1" FOREIGN KEY ("ID_AUTEUR")
	  REFERENCES  "AUTEUR" ("ID_AUTEUR") ENABLE
   )
/
CREATE TABLE  "REFORMATION" 
   (	"ID_REF" NUMBER NOT NULL ENABLE, 
	"ID_MATERIEL" NUMBER NOT NULL ENABLE, 
	"ID_DEPARTEMENT" NUMBER NOT NULL ENABLE, 
	"ETATACCEPT" VARCHAR2(4000), 
	"DATE_REFORME" DATE NOT NULL ENABLE, 
	 CONSTRAINT "REFORMATION_PK" PRIMARY KEY ("ID_REF") ENABLE, 
	 CONSTRAINT "REFORMATION_FK" FOREIGN KEY ("ID_MATERIEL")
	  REFERENCES  "MATERIEL" ("ID_MATERIEL") ENABLE, 
	 CONSTRAINT "REFORMATION_FK3" FOREIGN KEY ("ID_DEPARTEMENT")
	  REFERENCES  "DEPARTEMENT" ("ID_DEPARTEMENT") ENABLE
   )
/